# Generated by Django 5.0.2 on 2025-06-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('admin', 'Administeator'), ('product_manager', 'Producr Manager'), ('buyer', 'Buyer')], default='buyer', max_length=32),
        ),
    ]
