# Generated by Django 5.0.2 on 2025-06-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_useraccount_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('product_manager', 'Producr Manager'), ('buyer', 'Buyer')], default='buyer', max_length=32),
        ),
    ]
